<?php
/**
 * EvalContextTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ayaya\FlagrClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ayaya\FlagrClient;

/**
 * EvalContextTest Class Doc Comment
 *
 * @category    Class
 * @description EvalContext
 * @package     Ayaya\FlagrClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvalContextTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EvalContext"
     */
    public function testEvalContext()
    {
    }

    /**
     * Test attribute "entityID"
     */
    public function testPropertyEntityID()
    {
    }

    /**
     * Test attribute "entityType"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "entityContext"
     */
    public function testPropertyEntityContext()
    {
    }

    /**
     * Test attribute "enableDebug"
     */
    public function testPropertyEnableDebug()
    {
    }

    /**
     * Test attribute "flagID"
     */
    public function testPropertyFlagID()
    {
    }

    /**
     * Test attribute "flagKey"
     */
    public function testPropertyFlagKey()
    {
    }

    /**
     * Test attribute "flagTags"
     */
    public function testPropertyFlagTags()
    {
    }
}
