<?php
/**
 * EvalResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ayaya\FlagrClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ayaya\FlagrClient;

/**
 * EvalResultTest Class Doc Comment
 *
 * @category    Class
 * @description EvalResult
 * @package     Ayaya\FlagrClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvalResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EvalResult"
     */
    public function testEvalResult()
    {
    }

    /**
     * Test attribute "flagID"
     */
    public function testPropertyFlagID()
    {
    }

    /**
     * Test attribute "flagKey"
     */
    public function testPropertyFlagKey()
    {
    }

    /**
     * Test attribute "flagSnapshotID"
     */
    public function testPropertyFlagSnapshotID()
    {
    }

    /**
     * Test attribute "segmentID"
     */
    public function testPropertySegmentID()
    {
    }

    /**
     * Test attribute "variantID"
     */
    public function testPropertyVariantID()
    {
    }

    /**
     * Test attribute "variantKey"
     */
    public function testPropertyVariantKey()
    {
    }

    /**
     * Test attribute "variantAttachment"
     */
    public function testPropertyVariantAttachment()
    {
    }

    /**
     * Test attribute "evalContext"
     */
    public function testPropertyEvalContext()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "evalDebugLog"
     */
    public function testPropertyEvalDebugLog()
    {
    }
}
