<?php
/**
 * VariantApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ayaya\FlagrClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ayaya\FlagrClient;

use Ayaya\FlagrClient\Configuration;
use Ayaya\FlagrClient\ApiException;
use Ayaya\FlagrClient\ObjectSerializer;

/**
 * VariantApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ayaya\FlagrClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VariantApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createVariant
     *
     * .
     *
     */
    public function testCreateVariant()
    {
    }

    /**
     * Test case for deleteVariant
     *
     * .
     *
     */
    public function testDeleteVariant()
    {
    }

    /**
     * Test case for findVariants
     *
     * .
     *
     */
    public function testFindVariants()
    {
    }

    /**
     * Test case for putVariant
     *
     * .
     *
     */
    public function testPutVariant()
    {
    }
}
